before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - binary: "example"
    env:
      - CGO_ENABLED=0
    targets:
      - "linux_amd64"
archives:
  - replacements:
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
